### ISSUE TITLE
小白一枚，请问listfile.txt在哪里？

### ISSUE THREAD

**Issue by HuHongMing86** [tist0bsc/RSNA_Lung_Yolo_Pytorch#1]

**Comment by tist0bsc** [comment]
您指的是dataset.py里面的if语句的/tmp/listfile.txt么？如果是的话，是这样的。原始的yolo做的时候用的是voc07和voc12数据集，里面的图片路径和坐标是用xml文件存的，处理时需要先经过一步解析，把这些信息存到list里面，然后再用一个临时txt文件（就是这个/tmp/listfile.txt），把这些list都一个个写进去，最后生成batch的时候，再去那个txt里面读路径和坐标。我的这个案例中直接提供的就是txt，所以这一步就根本没执行。案例代码中的dataset.py是在原始yolo的dataset.py基础上修改的，这个if语句当时搞忘记删了，不知道我讲清楚了没有

**Comment by HuHongMing86** [comment]
> 您指的是dataset.py里面的if语句的/tmp/listfile.txt么？如果是的话，是这样的。原始的yolo做的时候用的是voc07和voc12数据集，里面的图片路径和坐标是用xml文件存的，处理时需要先经过一步解析，把这些信息存到list里面，然后再用一个临时txt文件（就是这个/tmp/listfile.txt），把这些list都一个个写进去，最后生成batch的时候，再去那个txt里面读路径和坐标。我的这个案例中直接提供的就是txt，所以这一步就根本没执行。案例代码中的dataset.py是在原始yolo的dataset.py基础上修改的，这个if语句当时搞忘记删了，不知道我讲清楚了没有

感激感激

**Comment by HuHongMing86** [comment]
还有一个问题， 我在运行train.py的时候 总是显示由于目标计算机积极拒绝，无法连接，貌似时visdom的问题，当时我的visdom是可以正常打开的，google了很多方法都没有解决，您在运行的时候有没有遇到过这种问题？

**Comment by HuHongMing86** [comment]
还有个问题，我在运行train.py的时候，代码报出错误如下
raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
google了很久都没有找到解决方案，可否指点一下？

**Comment by HuHongMing86** [comment]
还有个问题， google了很久都没有解决
在运行train.py的时候 报错
ValueError: Caught ValueError in DataLoader worker process 0.
我把DataLoader里面的numworks改成0后 又报错
在这句im_lr = np.fliplr(im).copy()
Input must be >= 2-d.
应该如何解决？求指点

**Comment by tist0bsc** [comment]
是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看

**Comment by tist0bsc** [comment]
> 
> 
> 还有个问题， google了很久都没有解决
> 在运行train.py的时候 报错
> ValueError: Caught ValueError in DataLoader worker process 0.
> 我把DataLoader里面的numworks改成0后 又报错
> 在这句im_lr = np.fliplr(im).copy()
> Input must be >= 2-d.
> 应该如何解决？求指点

是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看

**Comment by HuHongMing86** [comment]
运行eval_voc的时候报这个错误：
NameError: name 'VOC_CLASSES' is not defined

**Comment by HuHongMing86** [comment]
> 您指的是dataset.py里面的if语句的/tmp/listfile.txt么？如果是的话，是这样的。原始的yolo做的时候用的是voc07和voc12数据集，里面的图片路径和坐标是用xml文件存的，处理时需要先经过一步解析，把这些信息存到list里面，然后再用一个临时txt文件（就是这个/tmp/listfile.txt），把这些list都一个个写进去，最后生成batch的时候，再去那个txt里面读路径和坐标。我的这个案例中直接提供的就是txt，所以这一步就根本没执行。案例代码中的dataset.py是在原始yolo的dataset.py基础上修改的，这个if语句当时搞忘记删了，不知道我讲清楚了没有

那这个具体在dataset.py代码里面应该如何改写呢？我感觉我是这个地方不知道如何改才导致了后面的文件跑不动，望您给予指导，谢谢！

**Comment by HuHongMing86** [comment]
如果dataste.py那个if语句没有执行的话，我再运行train.py的时候报出如下错误
num_samples should be a positive integer value, but got num_samples=0
是这句话导致的
train_loader = DataLoader(train_dataset,batch_size=batch_size,shuffle=True,num_workers=4)
是图片没有读取进去么？请问应该如何修改？

**Comment by HuHongMing86** [comment]
> > 还有个问题， google了很久都没有解决
> > 在运行train.py的时候 报错
> > ValueError: Caught ValueError in DataLoader worker process 0.
> > 我把DataLoader里面的numworks改成0后 又报错
> > 在这句im_lr = np.fliplr(im).copy()
> > Input must be >= 2-d.
> > 应该如何解决？求指点
> 
> 是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看

69行打了断点后再往后调试就直接显示变量不可用， 然后报错
num_samples should be a positive integer value, but got num_samples=0

**Comment by tist0bsc** [comment]
> 
> 
> 运行eval_voc的时候报这个错误：
> NameError: name 'VOC_CLASSES' is not defined

不可能啊，VOC_CLASSES是在predict.py里面定义的，在evol_voc.py里面引入了predict.py里面的内容，你确定这两文件是在同一文件夹下面？在运行python代码的时候，最好路径不要太深，不要带中文，不然会有一些奇怪的报错

**Comment by tist0bsc** [comment]
> 
> 
> 如果dataste.py那个if语句没有执行的话，我再运行train.py的时候报出如下错误
> num_samples should be a positive integer value, but got num_samples=0
> 是这句话导致的
> train_loader = DataLoader(train_dataset,batch_size=batch_size,shuffle=True,num_workers=4)
> 是图片没有读取进去么？请问应该如何修改？

那个if没有任何影响，删不删都一样

**Comment by tist0bsc** [comment]
> 
> 
> > 您指的是dataset.py里面的if语句的/tmp/listfile.txt么？如果是的话，是这样的。原始的yolo做的时候用的是voc07和voc12数据集，里面的图片路径和坐标是用xml文件存的，处理时需要先经过一步解析，把这些信息存到list里面，然后再用一个临时txt文件（就是这个/tmp/listfile.txt），把这些list都一个个写进去，最后生成batch的时候，再去那个txt里面读路径和坐标。我的这个案例中直接提供的就是txt，所以这一步就根本没执行。案例代码中的dataset.py是在原始yolo的dataset.py基础上修改的，这个if语句当时搞忘记删了，不知道我讲清楚了没有
> 
> 那这个具体在dataset.py代码里面应该如何改写呢？我感觉我是这个地方不知道如何改才导致了后面的文件跑不动，望您给予指导，谢谢！

**Comment by tist0bsc** [comment]
> 
> 
> > > 还有个问题， google了很久都没有解决
> > > 在运行train.py的时候 报错
> > > ValueError: Caught ValueError in DataLoader worker process 0.
> > > 我把DataLoader里面的numworks改成0后 又报错
> > > 在这句im_lr = np.fliplr(im).copy()
> > > Input must be >= 2-d.
> > > 应该如何解决？求指点
> > 
> > 
> > 是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看
> 
> 69行打了断点后再往后调试就直接显示变量不可用， 然后报错
> num_samples should be a positive integer value, but got num_samples=0

你这报错，说的是num_samples里面是个空的，num_samples对应的又是self.boxes，这个是根据读取的数据处理生成的，所以大概率是你数据没读进来，所以，你在dataset.py的61行那里打个断点看看，首先确定一下是不是路径的问题，切记，为了路径里面最好不要有中文，路径要短。

**Comment by HuHongMing86** [comment]
> > > > 还有个问题， google了很久都没有解决
> > > > 在运行train.py的时候 报错
> > > > ValueError: Caught ValueError in DataLoader worker process 0.
> > > > 我把DataLoader里面的numworks改成0后 又报错
> > > > 在这句im_lr = np.fliplr(im).copy()
> > > > Input must be >= 2-d.
> > > > 应该如何解决？求指点
> > > 
> > > 
> > > 是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看
> > 
> > 
> > 69行打了断点后再往后调试就直接显示变量不可用， 然后报错
> > num_samples should be a positive integer value, but got num_samples=0
> 
> 你这报错，说的是num_samples里面是个空的，num_samples对应的又是self.boxes，这个是根据读取的数据处理生成的，所以大概率是你数据没读进来，所以，你在dataset.py的61行那里打个断点看看，首先确定一下是不是路径的问题，切记，为了路径里面最好不要有中文，路径要短。

61行打了断点以后和69行打断点效果相同，路径检查过了没有中文，但是还是报
num_samples should be a positive integer value, but got num_samples=0
这个错误

**Comment by HuHongMing86** [comment]
> > > > > 还有个问题， google了很久都没有解决
> > > > > 在运行train.py的时候 报错
> > > > > ValueError: Caught ValueError in DataLoader worker process 0.
> > > > > 我把DataLoader里面的numworks改成0后 又报错
> > > > > 在这句im_lr = np.fliplr(im).copy()
> > > > > Input must be >= 2-d.
> > > > > 应该如何解决？求指点
> > > > 
> > > > 
> > > > 是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看
> > > 
> > > 
> > > 69行打了断点后再往后调试就直接显示变量不可用， 然后报错
> > > num_samples should be a positive integer value, but got num_samples=0
> > 
> > 
> > 你这报错，说的是num_samples里面是个空的，num_samples对应的又是self.boxes，这个是根据读取的数据处理生成的，所以大概率是你数据没读进来，所以，你在dataset.py的61行那里打个断点看看，首先确定一下是不是路径的问题，切记，为了路径里面最好不要有中文，路径要短。
> 
> 61行打了断点以后和69行打断点效果相同，路径检查过了没有中文，但是还是报
> num_samples should be a positive integer value, but got num_samples=0
> 这个错误

路径也不长 我的py文件都在一个目录下 只有test和train是文件夹

**Comment by HuHongMing86** [comment]
> > > > > > 还有个问题， google了很久都没有解决
> > > > > > 在运行train.py的时候 报错
> > > > > > ValueError: Caught ValueError in DataLoader worker process 0.
> > > > > > 我把DataLoader里面的numworks改成0后 又报错
> > > > > > 在这句im_lr = np.fliplr(im).copy()
> > > > > > Input must be >= 2-d.
> > > > > > 应该如何解决？求指点
> > > > > 
> > > > > 
> > > > > 是不是你的输入有问题，你看看数据读没读进来，在dataset.py的第69行那里打个断点看看
> > > > 
> > > > 
> > > > 69行打了断点后再往后调试就直接显示变量不可用， 然后报错
> > > > num_samples should be a positive integer value, but got num_samples=0
> > > 
> > > 
> > > 你这报错，说的是num_samples里面是个空的，num_samples对应的又是self.boxes，这个是根据读取的数据处理生成的，所以大概率是你数据没读进来，所以，你在dataset.py的61行那里打个断点看看，首先确定一下是不是路径的问题，切记，为了路径里面最好不要有中文，路径要短。
> > 
> > 
> > 61行打了断点以后和69行打断点效果相同，路径检查过了没有中文，但是还是报
> > num_samples should be a positive integer value, but got num_samples=0
> > 这个错误
> 
> 路径也不长 我的py文件都在一个目录下 只有test和train是文件夹

txt文件和py文件也在同一目录下

**Comment by HuHongMing86** [comment]
不修改那个if语句，运行train.py还有这个错误
data init
系统找不到指定的路径。
Traceback (most recent call last):
  File "D:/JLU_PROJECT/train.py", line 58, in <module>
    train_dataset = yoloDataset(root=train_root,list_file=['RSNAtrain.txt'],train=True,transform = [transforms.ToTensor()] )
  File "D:\JLU_PROJECT\dataset.py", line 40, in __init__
    with open(list_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/listfile.txt'

**Comment by tist0bsc** [comment]
> 
> 
> 不修改那个if语句，运行train.py还有这个错误
> data init
> 系统找不到指定的路径。
> Traceback (most recent call last):
> File "D:/JLU_PROJECT/train.py", line 58, in
> train_dataset = yoloDataset(root=train_root,list_file=['RSNAtrain.txt'],train=True,transform = [transforms.ToTensor()] )
> File "D:\JLU_PROJECT\dataset.py", line 40, in **init**
> with open(list_file) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/listfile.txt'

呃，我这边刚刚在另外一台机器上面把这个代码git clone完测试了一下，是能正常运行的，我的torch版本是1.1.0，torchvision是0.2.0，if的那一段代码是不执行的，也不知道为什么你会报错。至于你eval_voc.py里的那个'VOC_CLASSES' is not defined的错误，你把predcit.py里面VOC_CLASSES的内容拷贝到eval_voc.py里面就肯定能正常运行了。如果你那个问题还是解决不了，如果你不介意的话可以给我邮箱发个向日葵，我进去调一调，123374696@163.com
![1618485392(1)](https://user-images.githubusercontent.com/34430361/114861135-717b1a80-9e1f-11eb-917b-37ec2a975cf4.jpg)

**Comment by HuHongMing86** [comment]
> > 不修改那个if语句，运行train.py还有这个错误
> > data init
> > 系统找不到指定的路径。
> > Traceback (most recent call last):
> > File "D:/JLU_PROJECT/train.py", line 58, in
> > train_dataset = yoloDataset(root=train_root,list_file=['RSNAtrain.txt'],train=True,transform = [transforms.ToTensor()] )
> > File "D:\JLU_PROJECT\dataset.py", line 40, in **init**
> > with open(list_file) as f:
> > FileNotFoundError: [Errno 2] No such file or directory: '/tmp/listfile.txt'
> 
> 呃，我这边刚刚在另外一台机器上面把这个代码git clone完测试了一下，是能正常运行的，我的torch版本是1.1.0，torchvision是0.2.0，if的那一段代码是不执行的，也不知道为什么你会报错。至于你eval_voc.py里的那个'VOC_CLASSES' is not defined的错误，你把predcit.py里面VOC_CLASSES的内容拷贝到eval_voc.py里面就肯定能正常运行了。如果你那个问题还是解决不了，如果你不介意的话可以给我邮箱发个向日葵，我进去调一调，[123374696@163.com](mailto:123374696@163.com)
> ![1618485392(1)](https://user-images.githubusercontent.com/34430361/114861135-717b1a80-9e1f-11eb-917b-37ec2a975cf4.jpg)

好的 是向日葵远程控制嘛？如果是的话 我稍后给您发
